### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by m-codebastards** [tryshoppe/shoppe#139]
Hi. Is there a roadmap (doc or something) with list of features and ideas? It would be great to see who is working on what and what is planned. 
What I like about shoppe is simplicity. I would be great to embrace KISS all the way, otherwise we can stop reinventing the wheel and move to spree now. I think we need some plan to not end up with pile random features. What's your opinion?

**Comment by cdesch** [comment]
I'm thinking the same. I really liked shoppe out of the box but if it isn't being maintained then I find it hard to subscribe.

**Comment by adamcooke** [comment]
Shoppe will continue to be maintained but it is designed to be very simple rather than having all the bells and whistles.

* If there are bug - they will be fixed.
* If there are new features which warrant adding - they will be added/merged.
* If a new version of Rails breaks it - it will be made compatible.

However, don't expect just to see commits for the sake of commits. Commits will happen when they are needed rather than just to maintain the illusion of a maintained project. I use Shoppe myself on a couple of sites which is my motivation for keeping it up to date. 

If you want to add big features or change the way things work significantly, Shoppe is probably not the platform for you - you can either write your own or use something like Spree. If you just need a simple store which allows customers to buy products - give it a go.
