### ISSUE TITLE
Internationalisation and Devise

### ISSUE THREAD

**Issue by drewpotter** [tryshoppe/shoppe#181]
Hello,

Would it be easy or possible to add the support for translations of product entries into different languages. So for example, a site can be viewed in English, Chinese, Arabic and French depending on the language of the customer.

I see there is rails i18n functionality, so I wonder how hard would this be to implement this in Shoppe?

Also I wonder if Devise can be made to work with Shoppe to allow customers to log in to the site?

Thanks

**Comment by andretanguy** [comment]
+1 for localisation related to products. Static pages can easily be localised using i18n, but there would need to be the ability to set local product names, categories etc in various languages

**Comment by cmnstmntmn** [comment]
:+1:

**Comment by andretanguy** [comment]
Have been working on this for a client today. We've taken the standard i18n Rails approach and made sure all templates use = t('.localised_content') and included gem 'route_translator' in our gemfile (for routing based on Locale set by the user). This works for localising all static pages, checkout funnel etc. Like you mention though, this doesn't take into account category and product localisation as this will need to be done from within the database.

**Comment by deanperry** [comment]
This would be do-able by adding extra database fields but then it would depend on the number of different languages so I'm not too sure how this would work as I've never worked on a multi-language web app

**Comment by andretanguy** [comment]
came across the same concern - in my mind, the logic would be to 'add alternative language(s)' in a settings area, so you define which you will support, then on the input forms, show some form of navigation element to switch between language variants. From a db perspective, you'll always have a 'parent' language (the default being :en) and then subsequent alternatives that are enabled.

All of the multi-lingual apps i've worked on have always had a specific end user in mind, so we've defined a max of 3 languages on an app level.

**Comment by andretanguy** [comment]
Ok, having thought this through a bit more, this is the approach I'm considering.

Preamble: Products have the ability to have many variants (with a parent_id set if its a sub-product). IMO, a similar logic should also be used for localisations based on the following:

- localisation needs to be per-product (name, description etc)
- it also needs to be per sku and permalink (need ability to set custom urls per language)
- you may want to charge different prices based on language set (charge French-speaking visitors an extra 5€, well, just because...)

This would essentially create 'products' in each language (add a new button at the top of each product#edit screen that is for 'Localisations' - works similar to variants does right now). Rather than these products having a 'parent_id', they would have a 'default_locale_id' field that references the primary language version (english by default).

I haven't yet thought about the implications on localisation for variants, but will jot ideas down when I get to that.

Localisation needs to be linked to the same 'locales' used by Rails i18n. If the developer then offers a multi-lingual approach, then when a user sets the locale, this will pull in the right localisations.

There are a few complexities to consider as this does go beyond the scope of the original Shoppe ethos. I think this would be better served as a shoppe module that can be included should someone want localisation.

**Comment by deanperry** [comment]
I've just created a PR for Localisations / Translations. #196 
Could you try it out @drewpotter and let me know how you get on?

**Comment by drewpotter** [comment]
Will have a look when I get the chance!

**Comment by andretanguy** [comment]
This feature will most likely be merged with master later today.

**Comment by deanperry** [comment]
This has been merged and is live on Rubygems (v1.0.8) #196
