### ISSUE TITLE
NoMethodError in Shoppe::Orders#index

### ISSUE THREAD

**Issue by Patrax** [tryshoppe/shoppe#189]
When going to myapp.com/shoppe/orders I get this error, any ideas? :)

    Showing /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/shoppe-1.0.5/app/views/shoppe/orders/index.html.haml where line #9 raised:

    undefined method `entry_name' for #<ActiveRecord::Relation []>
      
    6.        = link_to t('shoppe.orders.search_orders'), '#', :class => 'button', :rel => 'searchOrders'
    7.     %h2.orders
    8.       = t('shoppe.orders.orders')
    9.       %span= page_entries_info @orders
    10.   
    11.  = render 'search_form'

**Comment by deanperry** [comment]
Do you have `will_paginate` installed?

**Comment by Patrax** [comment]
I do, is that a conflict?

**Comment by Patrax** [comment]
Thank you Dean, I ended up commenting out:
    #gem 'will_paginate', '3.0.7'
    #gem 'bootstrap-will_paginate', '0.0.10'
and restarting the server and it worked. :)

**Comment by deanperry** [comment]
Ok, it's because shoppe is using kaminari for pagination. You can use them both together but I'm not sure what the code is off the top of my head





On Thu, May 14, 2015 at 8:56 AM -0700, "Patrax" <notifications@github.com> wrote:












Thank you Dean, I ended up commenting out:

    #gem 'will_paginate', '3.0.7'

    #gem 'bootstrap-will_paginate', '0.0.10'

and restarting the server and it worked. :)
