### ISSUE TITLE
Issue setting up category show page - missing column on products?

### ISSUE THREAD

**Issue by chbrown1293** [tryshoppe/shoppe#209]
I'm trying to set up a category show page but it appears im missing product_category_id column on products.

Here is what I have:

t.integer  "parent_id"
    t.string   "name"
    t.string   "sku"
    t.string   "permalink"
...

Any ideas for a course of action? 

Thanks

**Comment by laCour** [comment]
This is due to the introduction of multiple categories in 1.0.6.

**A single product's categories** (e.g. a product show page) can be accessed using [`product.product_categories`](http://www.rubydoc.info/gems/shoppe/1.0.7/Shoppe/Product#product_categories-instance_method). There is also [`product.product_category`](http://www.rubydoc.info/gems/shoppe/1.0.7/Shoppe/Product#product_category-instance_method) which is simply an alias for `product_categories.first`.

There is a more efficient way of doing this if you're **listing multiple products in categories**. In your controller, be sure to include the categories association on your products query:

```ruby
def index
  @products = Shoppe::Product.root.ordered.includes(:product_categories)
  @products = @products.group_by(&:product_category)
end
```

Then, in your view you can iterate over both categories and products as seen in the getting started tutorial: http://tryshoppe.com/docs/tutorials/products.

**Comment by deanperry** [comment]
The documentation has now been updated - http://tryshoppe.com/docs/tutorials/products - and you can see the example shop code here - https://github.com/tryshoppe/shoppe-example
